version: "3.9"

services:
  cevor_nginx_image:
    image: "nginx:1.23-alpine"

  cevor_postgres_image:
    image: "postgres:15.1-alpine"

  cevor_node_image:
    image: "node:19.3-alpine"

  cevor_python_image:
    image: "python:3.11-bullseye"

  cevor_rust:
    image: "rust:1.66-bullseye"
