version: "3.9"

services:
  cevor_nginx_image:
    image: "nginx:alpine"

  cevor_postgres_image:
    image: "postgres:alpine"

  cevor_node_image:
    image: "node:alpine"

  cevor_python_image:
    image: "python:slim"

  cevor_rust:
    image: "rust:slim"
